src/web/user/views.py
# user/views.py


import time
import stathat
import cookies
import rethinkdb as r
from rethinkdb.errors import RqlDriverError

from flask import g, abort, make_response, Blueprint, request, redirect, \
    url_for, render_template, flash


from users import User
from user.forms import SignupForm, LoginForm
from token import generate_confirmation_token, confirm_token


user_blueprint = Blueprint('user', __name__,)

from web import app, verifyLogin


@user_blueprint.before_app_request
def before_request():
    '''
    This function establishes a connection
    to the rethinkDB before each connection
    '''
    try:
        g.rdb_conn = r.connect(
            host=app.config['DBHOST'], port=app.config['DBPORT'],
            auth_key=app.config['DBAUTHKEY'], db=app.config['DATABASE'])
    except RqlDriverError:                      # pragma: no cover
        # If no connection possible throw 503 error
        abort(503, "No Database Connection \
                    Could be Established.")     # pragma: no cover


@user_blueprint.teardown_app_request
def teardown_request(exception):
    ''' This function closes the database connection when done '''
    try:
        g.rdb_conn.close()
    except AttributeError:  # pragma: no cover
        # Who cares?
        pass                # pragma: no cover


###########################
### User View Functions ###
###########################

# Signup
@user_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    '''
    User Sign up page: Very basic email + password
    sign up form that will also login users.
    '''
    # Data is used throughout for the jinja2 templates
    data = {
        'active': "signup",  # Sets the current page
        'loggedin': False  # Don't show the logout link
    }

    # Define the SignupForm
    form = SignupForm(request.form)
    # Validate and then create userdata
    if request.method == "POST":
        if form.validate():
            # Take form data
            email = form.email.data
            password = form.password.data
            company = form.company.data
            contact = form.contact.data
            userdata = {
                'username': email,
                'email': email,
                'password': password,
                'company': company,
                'contact': contact
            }

            # Create user
            user = User()
            user.config = app.config
            result = user.createUser(userdata, g.rdb_conn)
            # Check results for success or failure
            if result == "exists":
                flash('User already exists.', 'danger')
            elif result is not False:
                try:
                    stathat.ez_count(
                        app.config['STATHAT_EZ_KEY'],
                        app.config['ENVNAME'] + ' User Signup', 1)
                except:
                    pass
                print("/signup - New user created")
                cdata = cookies.genCdata(result, app.config['SECRET_KEY'])
                data['loggedin'] = True
                flash('You are signed up.', 'success')

                # Generate confirmation token
                generate_confirmation_token(email, result, time.time())

                # Build response
                resp = make_response(redirect(url_for('member.dashboard_page')))
                timeout = int(time.time()) + int(app.config['COOKIE_TIMEOUT'])
                # Set the cookie secure as best as possible
                resp.set_cookie(
                    'loggedin', cdata, expires=timeout, httponly=True)
                return resp
        else:
            stathat.ez_count(
                app.config['STATHAT_EZ_KEY'],
                app.config['ENVNAME'] + ' False User Signup', 1)
            print("/signup - False user creation")
            flash('Form is not valid.', 'danger')

    # Return Signup Page
    return render_template('user/signup.html', data=data, form=form)


# Login
@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_page():
    ''' User login page: This is a basic login page'''
    data = {
        'active': 'login',
        'loggedin': False
    }

    # Define and Validate the form
    form = LoginForm(request.form)
    if request.method == "POST":
        if form.validate():
            email = form.email.data
            password = form.password.data

            # Start user definition
            user = User()
            user.config = app.config
            if user.get('username', email, g.rdb_conn):
                result = user.checkPass(password, g.rdb_conn)
                if result is True:
                    data['loggedin'] = True
                    print("/login - User login successful")
                    flash('You are logged in.', 'success')
                    # Start building response
                    resp = make_response(
                        redirect(url_for('member.dashboard_page')))
                    cdata = cookies.genCdata(
                        user.uid, app.config['SECRET_KEY'])
                    timeout = int(time.time()) + \
                        int(app.config['COOKIE_TIMEOUT'])
                    # Set cookie as securely as possible
                    resp.set_cookie(
                        'loggedin', cdata, expires=timeout, httponly=True)
                    print("Setting cookie")
                    return resp
                else:
                    print("/login - User login error: wrong password")
                    flash('Password does not seem valid.', 'danger')
            else:
                print("/login - User login error: invalid user")
                flash('Uhh... User not found.', 'danger')
        else:
            print("/login - User login error: invalid form")
            flash('Form is not valid.', 'danger')

    # Return Login Page
    return render_template('user/login.html', data=data, form=form)


# Logout
@user_blueprint.route('/logout')
def logout_page():
    ''' User logout page: This will unset the cookie '''
    resp = make_response(redirect(url_for('user.login_page')))
    resp.set_cookie('loggedin', 'null', max_age=0)
    print("/logout - User logout")
    return resp


# Confirm Token
@user_blueprint.route('/confirm/<token>')
def confirm_email(token):
    verify = verifyLogin(
        app.config['SECRET_KEY'], app.config['COOKIE_TIMEOUT'], request.cookies)
    if verify:
        user = User()
        user.config = app.config
        user.get('uid', verify, g.rdb_conn)
        if user.confirmed:
            flash('Account already confirmed. Thank you.', 'success')
            return redirect(url_for('member.dashboard_page'))
        else:
            try:
                email = confirm_token(token)
                if user.email == email[0]:
                    r.table('users').get(verify).update(
                        {'confirmed': True}).run(g.rdb_conn)
                    flash('You have confirmed your account. Thanks!', 'success')
                    return redirect(url_for('member.dashboard_page'))
                else:
                    flash('The confirmation link is invalid.', 'danger')
                    return redirect(url_for('user.login_page'))
            except:
                flash('The confirmation link is invalid or has expired.',
                      'danger')
                return redirect(url_for('user.login_page'))
    else:
        flash('Please Login.', 'warning')
        return redirect(url_for('user.login_page'))

src/web/templates/base-header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- SEO Stuffz -->
    <title>Runbook - Monitoring with Automated Remediation for DevOps</title>
    <meta name="description" content="Solve problems in your sleep with IFTTT-style mitigation of DevOps issues">
    <meta name="keywords" content="CloudFlare DNS, CloudFlare, Runbook, Heroku Autoscaling, DNS Failover, Cloud DNS, High Availability, Static IP, Load Balancing, Domain Name, DNS, Nagios, BMC, Zenoss, Datadog, Cloud Monitoring, Monitoring Automation, Cloud Servers, Cloud Services, Server, App Developers, Server Monitoring">
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="Runbook - Monitoring with Automated Remediation for DevOps"/>
    <meta property="og:description" content="Solve problems in your sleep with IFTTT-style mitigation of DevOps issues"/>
    <meta property="og:site_name" content="Runbook"/>
    <meta property="og:image" content="{{url_for('static', filename='img/logos/png/runbook_logo_sleep_color_on_white.png')}}"/>

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/darkly/bootstrap.min.css" rel="stylesheet">
    <link href="{{url_for('static', filename='css/dashboard.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/bootstrap-multiselect.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/c3.css')}}" rel="stylesheet">


    {% block css %}{% endblock %}

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    {% for item in data['js_header'] %}
        {% include item %}
    {% endfor %}

  </head>

  <body>
    <div class="navbar navbar-default navbar-static-top navigation-menu {{ 'clear' if data['clean_header'] }}" role="navigation">
      <div class="container header">
        <div class="navbar-header">
          <a href="{{ url_for('public.index_redirect') }}" class="header-logo">
          <img src="/static/img/logos/png/runbook_white_logo_color_on_white_small.png" width="100%" alt="Runbook">
          </a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         </div>
         <div class="navbar-collapse navbar-right collapse">
           <ul class="nav navbar-nav navigation-nav">
            {% if data['loggedin'] == False %}
              <li>
                <a href="https://runbook.readthedocs.org/en/master/">Documentation</a>
              </li>
              <li>
                <a href="{{ url_for('user.login_page') }}">Login</a>
              </li>
              <li>
                <a href="{{ url_for('user.signup') }}">Create Account</a>
              </li>
            {% else %}
{% if data['url'] == '/dashboard' %}
        <li class="active"><a href="/dashboard"><i class="fa fa-book"></i> Runbooks</a></li>
        {% else %}
        <li><a href="/dashboard"><i class="fa fa-book"></i> Runbooks</a></li>
        {% endif %}
        {% if "manage" in data['url'] %}<li class="active">{%- else -%}<li>{%- endif -%}
        <a href="/dashboard/manage-reactions"><i class="fa fa-flask"></i> Reactions</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria=expanded="false"><i class="fa fa-plus"></i> Create New</a>
          <ul class="dropdown-menu">
            <li><a href="/dashboard/monitors"><i class="fa fa-book"></i> Runbook</a></li>
            <li><a href="/dashboard/reactions"><i class="fa fa-flask"></i> Reaction</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> {{ data['username'] }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if data['url'] == '/dashboard/user-preferences' %}
            <li class="active"><a href="/dashboard/user-preferences">Preferences</a></li>
            {% else %}
            <li><a href="/dashboard/user-preferences">Preferences</a></li>
            {% endif %}
            {% if data['url'] == '/dashboard/mod-subscription' %}
            <li class="active"><a href="/dashboard/mod-subscription">Subscription</a></li>
            {% else %}
            <li><a href="/dashboard/mod-subscription">Subscription</a></li>
            {% endif %}
            <li role="separator" class="divider"></li>
            <li>
              <a href="{{ url_for('user.logout_page') }}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </li>
        </ul>
        </div>
      </div>
    </div>
    <!-- messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    {% endwith %}

src/web/templates/dash-footer.html
  <div class="dash-footer container">
    <div class="row">
     <div class="col-lg-12">
      <hr>
      <p class="text-muted credit text-right">Powered by <a href="https://github.com/Runbook" target="_blank">Runbook</a>.</p>
    </div>
   </div>
  </div>
  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{{url_for('static', filename='js/bootstrap-multiselect.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/list.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/list.pagination.min.js')}}" type="text/javascript"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('.multiselect').multiselect({
        enableCaseInsensitiveFiltering: true,
        filterBehavior: 'both',
        filterPlaceholder: 'Search',
        buttonClass: 'form-control',
        numberDisplayed: 1,
        maxHeight: 400,
      });

      $('.select').multiselect({
        buttonClass: 'form-control',
        enableCaseInsensitiveFiltering: true,
        filterBehavior: 'both',
        filterPlaceholder: 'Search',
        maxHeight: 400,
      });

      $('.plan-select').multiselect({
        buttonClass: 'form-control',
        maxHeight: 400,
      });


    });

  </script>
  {% for item in data['js_bottom'] %}
    {% include item %}
  {% endfor %}
  {% block js %}{% endblock %}
  <script type="text/javascript">
    $(document).ready(function(){
  $('.slick').slick({
  slidesToShow: 1,
  slidesToScroll: 1,
  autoplay: true,
  autoplaySpeed: 2000,
  arrows: false,
  fade: true,
  });
});
        
        
  </script>
  </body>
</html>

src/web/templates/sidebar.html
    <div class="col-md-4">
      <h4>Menu:</h4>
      <ul class="nav nav-pills nav-stacked">
        {% if data['url'] == '/dashboard' %}
        <li class="active"><a href="/dashboard"><i class="fa fa-area-chart fa-lg"></i>&nbsp;&nbsp;Status</a></li>
        {% else %}
        <li><a href="/dashboard"><i class="fa fa-area-chart fa-lg"></i>&nbsp;&nbsp;Status</a></li>
        {% endif %}
        {% if "monitors" in data['url'] %}<li class="active">{%- else -%}<li>{%- endif -%}
        <a href="/dashboard/monitors"><i class="fa fa-book fa-lg"></i>&nbsp;&nbsp;Runbooks</a></li>
        {% if "reactions" in data['url'] %}<li class="active">{%- else -%}<li>{%- endif -%}
        <a href="/dashboard/reactions"><i class="fa fa-flask fa-lg"></i>&nbsp;&nbsp;Reactions</a></li>
        {% if data['url'] == '/dashboard/mod-subscription' %}
        <li class="active"><a href="/dashboard/mod-subscription"><i class="fa fa-refresh fa-lg"></i>&nbsp;&nbsp;Subscription</a></li>
        {% else %}
        <li><a href="/dashboard/mod-subscription"><i class="fa fa-refresh fa-lg"></i>&nbsp;&nbsp;Subscription</a></li>
        {% endif %}
        {% if data['url'] == '/dashboard/user-preferences' %}
        <li class="active"><a href="/dashboard/user-preferences"><i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;User Preferences</a></li>
        {% else %}
        <li><a href="/dashboard/user-preferences"><i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;User Preferences</a></li>
        {% endif %}
        <li><a href="mailto:support@runbook.io"><i class="fa fa-envelope fa-lg"></i>&nbsp;&nbsp;Contact Support</a></li>
      </ul>
      {% if data['upgraded'] == False %}
      <h5>Special Offers:</h5>
      <ul class="nav nav-pills nav-stacked">
        <li>
        <a href="https://www.digitalocean.com/?refcode=4c1c0f8027bb" target="_blank">Get a $10 credit with DigitalOcean</a>
        </li>
      </ul>
      {% endif %}
    </div>